### ISSUE TITLE
[Tag]이슈 예시입니다

### ISSUE THREAD

**Issue by ryan-g00** [prgrms-fe-devcourse/NFE1_2_MUX#1]
## 🛠️ 만들고자 하는 기능
- 기능 내용 요약 설명

## 📝 구현 내용
- [ ] 구현 내용 1
- [ ] 구현 내용 2

## 🗓️ 개발 일정
00월 00일 ~ 00월 00일

**Comment by ryan-g00** [comment]
[feat]: commit 메세지 작성

**Comment by hjlee2778** [comment]
좋은 방법인 것 같습니다.

**Comment by Hyun-bin-Kim** [comment]
아이우
